// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MyContainer: typeof import('./components/myContainer/myContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/sideBar/index.vue')['default']
    SideBarItem: typeof import('./components/sideBar/sideBarItem.vue')['default']
    SubmitButton: typeof import('./components/submitButton/submitButton.vue')['default']
  }
}

export {}
